# Generated by Django 5.2.8 on 2025-11-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ('id',), 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ('id',), 'verbose_name': 'Кашелек', 'verbose_name_plural': 'Кашельки'},
        ),
    ]
