# Generated by Django 5.2.8 on 2025-11-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_operation_options_alter_wallet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ('id',), 'verbose_name': 'Кошелек', 'verbose_name_plural': 'Кошельки'},
        ),
    ]
